name: Build and test

on: [push, pull_request]

# env:
#   OPAMVERBOSE: 3

jobs:
  test:
    name: Run examples on both architectures
    runs-on: macos-latest
    steps:
      - name: Install GNU utils
        run: |
          brew install make gnu-sed
          echo "/opt/homebrew/opt/make/libexec/gnubin" >> "$GITHUB_PATH"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install OCaml compiler
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0
      - name: Pin and install Unikraft
        run: |
          sed 's/version:.*/version: "dev"/' unikraft.0.18.0.opin > o
          OPAMEDITOR="cp o" opam pin add --edit -y unikraft - < /dev/null
      - name: Install extra packages
        run: |
          opam install dune
      - name: Install arch-specific packages
        run: |
          opam install                                \
            ocaml-unikraft-x86_64                     \
            ocaml-unikraft-backend-qemu-x86_64        \
            ocaml-unikraft-backend-firecracker-x86_64 \
            ocaml-unikraft-arm64                      \
            ocaml-unikraft-backend-qemu-arm64         \
            ocaml-unikraft-backend-firecracker-arm64
      - name: Show configuration
        run: |
          opam exec -- ocamlc -config
          opam config list
          opam list
      - name: Install default packages
        run: |
          opam install                    \
            ocaml-unikraft                \
            ocaml-unikraft-default-arm64  \
            ocaml-unikraft-backend-qemu   \
            ocaml-unikraft-backend-firecracker
      - name: Show toolchain configuration
        run: |
          opam exec -- ocamlfind -toolchain unikraft ocamlc -config
      - name: Test examples
        run: |
          cd examples/simple/
          opam exec -- dune build
          cd ../all/
          opam exec -- dune runtest
